version: '3'
services:
  dashboard:
    build: .
    image: ags131/screepsdashboard
    volumes:
    - ./settings.yaml:/app/settings.yaml
    ports:
    - '5000:5000'
  logger:
    build: .
    image: ags131/screepsdashboard
    command:
    - screepsdashboard
    - log
    volumes:
    - ./settings.yaml:/app/settings.yaml
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
    - '5601:5601'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
    - 'discovery.type=single-node'